export const tables = {
  roles: {
    columns: ["id", "name", "description", "permissions", "created_at", "updated_at"],
    rows: [
      { id: 1, name: "admin", description: "Platform administrator", permissions: '["all"]', created_at: "2024-01-01 00:00:00", updated_at: "2024-01-01 00:00:00" },
      { id: 2, name: "vendor", description: "Merchant/seller account", permissions: '["products.manage","orders.view"]', created_at: "2024-01-01 00:00:00", updated_at: "2024-01-01 00:00:00" },
      { id: 3, name: "customer", description: "Regular buyer account", permissions: '["orders.place","reviews.write"]', created_at: "2024-01-01 00:00:00", updated_at: "2024-01-01 00:00:00" },
    ],
  },
  users: {
    columns: ["id", "role_id", "name", "email", "phone", "is_email_verified", "status", "last_login_at", "created_at"],
    rows: [
      { id: 1,   role_id: 1, name: "Admin 1",         email: "admin1@estore.com",    phone: "+91900000001", is_email_verified: 1, status: "active",   last_login_at: "2025-07-01 10:00:00", created_at: "2024-01-01 00:00:00" },
      { id: 2,   role_id: 1, name: "Admin 2",         email: "admin2@estore.com",    phone: "+91900000002", is_email_verified: 1, status: "active",   last_login_at: "2025-07-02 09:30:00", created_at: "2024-01-01 00:00:00" },
      { id: 6,   role_id: 2, name: "Rajesh Kumar 1",  email: "vendor1@shop.com",     phone: "+91800000001", is_email_verified: 1, status: "active",   last_login_at: "2025-06-28 14:00:00", created_at: "2024-02-10 00:00:00" },
      { id: 206, role_id: 3, name: "Aarav Shah #1",   email: "customer1@gmail.com",  phone: "+91700000001", is_email_verified: 1, status: "inactive", last_login_at: "2025-07-03 08:00:00", created_at: "2024-03-15 00:00:00" },
      { id: 207, role_id: 3, name: "Ishaan Patel #2", email: "customer2@gmail.com",  phone: "+91700000002", is_email_verified: 0, status: "banned",   last_login_at: null,                  created_at: "2024-04-20 00:00:00" },
    ],
  },
  vendors: {
    columns: ["id", "user_id", "store_name", "contact_email", "city", "commission_rate", "rating", "status", "approved_at"],
    rows: [
      { id: 1, user_id: 6,  store_name: "TechZone #1",     contact_email: "vendor1@shop.com", city: "Mumbai",    commission_rate: "12.50", rating: "4.20", status: "active",    approved_at: "2024-02-15 00:00:00" },
      { id: 2, user_id: 7,  store_name: "FashionHub #2",   contact_email: "vendor2@shop.com", city: "Delhi",     commission_rate: "11.00", rating: "3.80", status: "active",    approved_at: "2024-03-01 00:00:00" },
      { id: 3, user_id: 8,  store_name: "GadgetPlanet #3", contact_email: "vendor3@shop.com", city: "Bangalore", commission_rate: "13.75", rating: "4.50", status: "pending",   approved_at: null },
      { id: 4, user_id: 9,  store_name: "HomeNest #4",     contact_email: "vendor4@shop.com", city: "Chennai",   commission_rate: "10.25", rating: "3.60", status: "suspended", approved_at: "2024-03-10 00:00:00" },
      { id: 5, user_id: 10, store_name: "SportsPro #5",    contact_email: "vendor5@shop.com", city: "Hyderabad", commission_rate: "14.00", rating: "4.10", status: "active",    approved_at: "2024-04-05 00:00:00" },
    ],
  },
  categories: {
    columns: ["id", "parent_id", "name", "slug", "is_active", "display_order", "created_at"],
    rows: [
      { id: 1, parent_id: null, name: "Electronics", slug: "electronics", is_active: 1, display_order: 1, created_at: "2024-01-01 00:00:00" },
      { id: 2, parent_id: null, name: "Fashion", slug: "fashion", is_active: 1, display_order: 2, created_at: "2024-01-01 00:00:00" },
      { id: 3, parent_id: null, name: "Home & Living", slug: "home-living", is_active: 1, display_order: 3, created_at: "2024-01-01 00:00:00" },
      { id: 11, parent_id: 1, name: "Smartphones", slug: "smartphones", is_active: 1, display_order: 1, created_at: "2024-01-01 00:00:00" },
      { id: 12, parent_id: 1, name: "Laptops", slug: "laptops", is_active: 1, display_order: 2, created_at: "2024-01-01 00:00:00" },
    ],
  },
  products: {
    columns: ["id", "vendor_id", "category_id", "title", "sku", "price", "sale_price", "status", "is_featured", "created_at"],
    rows: [
      { id: 1, vendor_id: 2, category_id: 2, title: "Ultra HD Smart TV 55 inch - Model 1", sku: "SKU-000001", price: "32500.00", sale_price: null, status: "active", is_featured: 0, created_at: "2024-05-10 00:00:00" },
      { id: 2, vendor_id: 3, category_id: 3, title: "Running Shoes Air Cushion - Model 2", sku: "SKU-000002", price: "2999.00", sale_price: "2499.00", status: "inactive", is_featured: 0, created_at: "2024-05-11 00:00:00" },
      { id: 3, vendor_id: 4, category_id: 4, title: "Organic Green Tea 200g - Model 3", sku: "SKU-000003", price: "450.00", sale_price: "380.00", status: "draft", is_featured: 0, created_at: "2024-05-12 00:00:00" },
      { id: 4, vendor_id: 5, category_id: 5, title: "Leather Office Chair Ergonomic - Model 4", sku: "SKU-000004", price: "12800.00", sale_price: null, status: "deleted", is_featured: 0, created_at: "2024-05-13 00:00:00" },
      { id: 5, vendor_id: 1, category_id: 1, title: "DSLR Camera 24MP Kit - Model 5", sku: "SKU-000005", price: "48500.00", sale_price: null, status: "active", is_featured: 1, created_at: "2024-05-14 00:00:00" },
    ],
  },
  product_inventory: {
    columns: ["id", "product_id", "quantity_in_stock", "reserved_quantity", "reorder_level", "warehouse_location", "last_restocked_at"],
    rows: [
      { id: 1, product_id: 1, quantity_in_stock: 342, reserved_quantity: 5, reorder_level: 10, warehouse_location: "WH-2-BIN-001", last_restocked_at: "2025-06-01 00:00:00" },
      { id: 2, product_id: 2, quantity_in_stock: 87, reserved_quantity: 12, reorder_level: 10, warehouse_location: "WH-3-BIN-002", last_restocked_at: "2025-06-10 00:00:00" },
      { id: 3, product_id: 3, quantity_in_stock: 500, reserved_quantity: 0, reorder_level: 5, warehouse_location: "WH-4-BIN-003", last_restocked_at: "2025-05-20 00:00:00" },
      { id: 4, product_id: 4, quantity_in_stock: 23, reserved_quantity: 3, reorder_level: 10, warehouse_location: "WH-1-BIN-004", last_restocked_at: "2025-06-15 00:00:00" },
      { id: 5, product_id: 5, quantity_in_stock: 9, reserved_quantity: 1, reorder_level: 5, warehouse_location: "WH-5-BIN-005", last_restocked_at: "2025-07-01 00:00:00" },
    ],
  },
  carts: {
    columns: ["id", "user_id", "status", "total_amount", "coupon_code", "discount_amount", "created_at", "abandoned_at"],
    rows: [
      { id: 1, user_id: 207, status: "active", total_amount: "1299.00", coupon_code: null, discount_amount: "0.00", created_at: "2025-07-01 10:00:00", abandoned_at: null },
      { id: 2, user_id: 208, status: "abandoned", total_amount: "5499.00", coupon_code: null, discount_amount: "0.00", created_at: "2025-06-28 14:00:00", abandoned_at: "2025-06-29 10:00:00" },
      { id: 3, user_id: 209, status: "converted", total_amount: "3200.00", coupon_code: "SAVE20", discount_amount: "200.00", created_at: "2025-06-25 09:00:00", abandoned_at: null },
      { id: 4, user_id: 210, status: "active", total_amount: "899.00", coupon_code: null, discount_amount: "0.00", created_at: "2025-07-03 08:30:00", abandoned_at: null },
      { id: 5, user_id: 211, status: "abandoned", total_amount: "7800.00", coupon_code: null, discount_amount: "0.00", created_at: "2025-06-20 16:00:00", abandoned_at: "2025-06-21 12:00:00" },
    ],
  },
  cart_items: {
    columns: ["id", "cart_id", "product_id", "quantity", "unit_price", "added_at"],
    rows: [
      { id: 1, cart_id: 1, product_id: 7, quantity: 1, unit_price: "1299.00", added_at: "2025-07-01 10:05:00" },
      { id: 2, cart_id: 2, product_id: 14, quantity: 2, unit_price: "2749.50", added_at: "2025-06-28 14:10:00" },
      { id: 3, cart_id: 3, product_id: 21, quantity: 1, unit_price: "3200.00", added_at: "2025-06-25 09:15:00" },
      { id: 4, cart_id: 4, product_id: 3, quantity: 3, unit_price: "299.67", added_at: "2025-07-03 08:35:00" },
      { id: 5, cart_id: 5, product_id: 52, quantity: 1, unit_price: "7800.00", added_at: "2025-06-20 16:05:00" },
    ],
  },
  orders: {
    columns: ["id", "user_id", "order_number", "order_status", "payment_status", "total_amount", "subtotal", "shipping_amount", "tax_amount", "created_at"],
    rows: [
      { id: 1, user_id: 207, order_number: "ORD-2025-000001", order_status: "pending",    payment_status: "pending",            total_amount: "1599.00",  subtotal: "1500.00",  shipping_amount: "99.00", tax_amount: "0.00",   created_at: "2025-01-10 10:00:00" },
      { id: 2, user_id: 208, order_number: "ORD-2025-000002", order_status: "confirmed",  payment_status: "paid",               total_amount: "3499.00",  subtotal: "3200.00",  shipping_amount: "99.00", tax_amount: "200.00", created_at: "2025-02-14 11:30:00" },
      { id: 3, user_id: 209, order_number: "ORD-2025-000003", order_status: "processing", payment_status: "paid",               total_amount: "899.00",   subtotal: "850.00",   shipping_amount: "49.00", tax_amount: "0.00",   created_at: "2025-03-05 09:00:00" },
      { id: 4, user_id: 210, order_number: "ORD-2025-000004", order_status: "shipped",    payment_status: "failed",             total_amount: "12800.00", subtotal: "12500.00", shipping_amount: "0.00",  tax_amount: "300.00", created_at: "2025-04-01 08:00:00" },
      { id: 5, user_id: 211, order_number: "ORD-2025-000005", order_status: "delivered",  payment_status: "refunded",           total_amount: "5200.00",  subtotal: "5000.00",  shipping_amount: "0.00",  tax_amount: "200.00", created_at: "2025-04-18 14:00:00" },
      { id: 6, user_id: 212, order_number: "ORD-2025-000006", order_status: "cancelled",  payment_status: "partially_refunded", total_amount: "2100.00",  subtotal: "2000.00",  shipping_amount: "0.00",  tax_amount: "100.00", created_at: "2025-05-22 10:00:00" },
      { id: 7, user_id: 213, order_number: "ORD-2025-000007", order_status: "refunded",   payment_status: "refunded",           total_amount: "4750.00",  subtotal: "4500.00",  shipping_amount: "0.00",  tax_amount: "250.00", created_at: "2025-06-15 09:00:00" },
    ],
  },
  order_items: {
    columns: ["id", "order_id", "product_id", "vendor_id", "quantity", "unit_price", "total_price", "status", "return_status", "return_reason"],
    rows: [
      { id: 1, order_id: 1, product_id: 4, vendor_id: 5, quantity: 1, unit_price: "3200.00", total_price: "3200.00", status: "pending",   return_status: null,       return_reason: null },
      { id: 2, order_id: 2, product_id: 5, vendor_id: 1, quantity: 1, unit_price: "12500.00", total_price: "12500.00", status: "confirmed", return_status: null,       return_reason: null },
      { id: 3, order_id: 3, product_id: 2, vendor_id: 3, quantity: 2, unit_price: "425.00",   total_price: "850.00",   status: "shipped",   return_status: null,       return_reason: null },
      { id: 4, order_id: 4, product_id: 1, vendor_id: 2, quantity: 1, unit_price: "5000.00",  total_price: "5000.00",  status: "delivered", return_status: null,       return_reason: null },
      { id: 5, order_id: 5, product_id: 3, vendor_id: 4, quantity: 3, unit_price: "500.00",   total_price: "1500.00",  status: "cancelled", return_status: null,       return_reason: null },
      { id: 6, order_id: 6, product_id: 6, vendor_id: 3, quantity: 1, unit_price: "2000.00",  total_price: "2000.00",  status: "returned",  return_status: "approved", return_reason: "Defective product received" },
    ],
  },
  payments: {
    columns: ["id", "order_id", "user_id", "transaction_id", "payment_method", "payment_gateway", "amount", "status", "failure_reason", "created_at"],
    rows: [
      { id: 1, order_id: 1, user_id: 207, transaction_id: "TXN-abc123def456", payment_method: "upi",         payment_gateway: "razorpay", amount: "1599.00",  status: "pending",            failure_reason: null,                created_at: "2025-01-10 10:02:00" },
      { id: 2, order_id: 2, user_id: 208, transaction_id: "TXN-bcd234efg567", payment_method: "credit_card", payment_gateway: "stripe",   amount: "3499.00",  status: "success",            failure_reason: null,                created_at: "2025-02-14 11:32:00" },
      { id: 3, order_id: 3, user_id: 209, transaction_id: "TXN-cde345fgh678", payment_method: "debit_card",  payment_gateway: "paytm",    amount: "899.00",   status: "success",            failure_reason: null,                created_at: "2025-03-05 09:02:00" },
      { id: 4, order_id: 4, user_id: 210, transaction_id: "TXN-def456ghi789", payment_method: "netbanking",  payment_gateway: "cashfree", amount: "12800.00", status: "failed",             failure_reason: "Card declined",     created_at: "2025-04-01 08:02:00" },
      { id: 5, order_id: 5, user_id: 211, transaction_id: "TXN-efg567hij890", payment_method: "wallet",      payment_gateway: "paypal",   amount: "5200.00",  status: "refunded",           failure_reason: null,            created_at: "2025-04-18 14:02:00" },
      { id: 6, order_id: 6, user_id: 212, transaction_id: "TXN-fgh678ijk901", payment_method: "cod",         payment_gateway: "paytm",    amount: "2100.00",  status: "partially_refunded", failure_reason: null,            created_at: "2025-05-22 10:02:00" },
      { id: 7, order_id: 7, user_id: 213, transaction_id: "TXN-ghi789jkl012", payment_method: "emi",         payment_gateway: "cashfree", amount: "4750.00",  status: "refunded",           failure_reason: null,            created_at: "2025-06-15 09:02:00" },
      { id: 8, order_id: 1, user_id: 207, transaction_id: "TXN-hij890klm123", payment_method: "netbanking",  payment_gateway: "razorpay", amount: "1599.00",  status: "success",            failure_reason: null,            created_at: "2025-01-10 10:05:00" },
    ],
  },
  shipments: {
    columns: ["id", "order_id", "vendor_id", "tracking_number", "courier_partner", "shipping_method", "status", "estimated_delivery_date", "shipping_cost"],
    rows: [
      { id: 1, order_id: 1, vendor_id: 5, tracking_number: "TRACK-ABC123", courier_partner: "Delhivery",  shipping_method: "standard",  status: "pending",          estimated_delivery_date: "2025-01-15", shipping_cost: "0.00" },
      { id: 2, order_id: 2, vendor_id: 1, tracking_number: "TRACK-BCD234", courier_partner: "Bluedart",   shipping_method: "express",   status: "packed",           estimated_delivery_date: "2025-02-19", shipping_cost: "99.00" },
      { id: 3, order_id: 3, vendor_id: 3, tracking_number: "TRACK-CDE345", courier_partner: "FedEx",      shipping_method: "overnight", status: "dispatched",       estimated_delivery_date: "2025-03-10", shipping_cost: "49.00" },
      { id: 4, order_id: 4, vendor_id: 4, tracking_number: "TRACK-DEF456", courier_partner: "XpressBees", shipping_method: "standard",  status: "in_transit",       estimated_delivery_date: "2025-04-06", shipping_cost: "149.00" },
      { id: 5, order_id: 5, vendor_id: 2, tracking_number: "TRACK-EFG567", courier_partner: "DTDC",       shipping_method: "express",   status: "out_for_delivery", estimated_delivery_date: "2025-04-23", shipping_cost: "0.00" },
      { id: 6, order_id: 6, vendor_id: 3, tracking_number: "TRACK-FGH678", courier_partner: "Delhivery",  shipping_method: "standard",  status: "delivered",        estimated_delivery_date: "2025-05-27", shipping_cost: "0.00" },
      { id: 7, order_id: 7, vendor_id: 1, tracking_number: "TRACK-GHI789", courier_partner: "Bluedart",   shipping_method: "overnight", status: "returned",         estimated_delivery_date: "2025-06-20", shipping_cost: "99.00" },
      { id: 8, order_id: 2, vendor_id: 5, tracking_number: "TRACK-HIJ890", courier_partner: "FedEx",      shipping_method: "express",   status: "lost",             estimated_delivery_date: "2025-02-20", shipping_cost: "199.00" },
    ],
  },
  reviews: {
    columns: ["id", "product_id", "user_id", "order_id", "rating", "title", "is_verified_purchase", "helpful_votes", "status", "created_at"],
    rows: [
      { id: 1, product_id: 4, user_id: 207, order_id: 1, rating: 5, title: "Excellent product, highly recommend!", is_verified_purchase: 1, helpful_votes: 23, status: "published", created_at: "2025-02-10 00:00:00" },
      { id: 2, product_id: 5, user_id: 208, order_id: 2, rating: 4, title: "Good value for money",                 is_verified_purchase: 1, helpful_votes: 11, status: "published", created_at: "2025-03-01 00:00:00" },
      { id: 3, product_id: 2, user_id: 209, order_id: 3, rating: 3, title: "Average product, nothing special",     is_verified_purchase: 1, helpful_votes: 4,  status: "pending",   created_at: "2025-04-05 00:00:00" },
      { id: 4, product_id: 1, user_id: 210, order_id: 4, rating: 2, title: "Quality could be better",              is_verified_purchase: 1, helpful_votes: 7,  status: "rejected",  created_at: "2025-05-20 00:00:00" },
      { id: 5, product_id: 3, user_id: 211, order_id: 5, rating: 5, title: "Loved it! Will buy again",             is_verified_purchase: 1, helpful_votes: 31, status: "published", created_at: "2025-07-03 00:00:00" },
    ],
  },
};

export const tableTypes = {
  roles: {
    id: "INT", name: "VARCHAR", description: "TEXT", permissions: "JSON", created_at: "DATETIME", updated_at: "DATETIME",
  },
  users: {
    id: "INT", role_id: "INT", name: "VARCHAR", email: "VARCHAR", phone: "VARCHAR",
    is_email_verified: "TINYINT", status: "ENUM", last_login_at: "DATETIME", created_at: "DATETIME",
  },
  vendors: {
    id: "INT", user_id: "INT", store_name: "VARCHAR", contact_email: "VARCHAR", city: "VARCHAR",
    commission_rate: "DECIMAL", rating: "DECIMAL", status: "ENUM", approved_at: "DATETIME",
  },
  categories: {
    id: "INT", parent_id: "INT", name: "VARCHAR", slug: "VARCHAR",
    is_active: "TINYINT", display_order: "INT", created_at: "DATETIME",
  },
  products: {
    id: "INT", vendor_id: "INT", category_id: "INT", title: "VARCHAR", sku: "VARCHAR",
    price: "DECIMAL", sale_price: "DECIMAL", status: "ENUM", is_featured: "TINYINT", created_at: "DATETIME",
  },
  product_inventory: {
    id: "INT", product_id: "INT", quantity_in_stock: "INT", reserved_quantity: "INT",
    reorder_level: "INT", warehouse_location: "VARCHAR", last_restocked_at: "DATETIME",
  },
  carts: {
    id: "INT", user_id: "INT", status: "ENUM", total_amount: "DECIMAL",
    coupon_code: "VARCHAR", discount_amount: "DECIMAL", created_at: "DATETIME", abandoned_at: "DATETIME",
  },
  cart_items: {
    id: "INT", cart_id: "INT", product_id: "INT", quantity: "INT", unit_price: "DECIMAL", added_at: "DATETIME",
  },
  orders: {
    id: "INT", user_id: "INT", order_number: "VARCHAR", order_status: "ENUM", payment_status: "ENUM",
    total_amount: "DECIMAL", subtotal: "DECIMAL", shipping_amount: "DECIMAL", tax_amount: "DECIMAL", created_at: "DATETIME",
  },
  order_items: {
    id: "INT", order_id: "INT", product_id: "INT", vendor_id: "INT",
    quantity: "INT", unit_price: "DECIMAL", total_price: "DECIMAL", status: "VARCHAR",
    return_status: "VARCHAR", return_reason: "TEXT",
  },
  payments: {
    id: "INT", order_id: "INT", user_id: "INT", transaction_id: "VARCHAR",
    payment_method: "ENUM", payment_gateway: "ENUM", amount: "DECIMAL",
    status: "ENUM", failure_reason: "VARCHAR", created_at: "DATETIME",
  },
  shipments: {
    id: "INT", order_id: "INT", vendor_id: "INT", tracking_number: "VARCHAR",
    courier_partner: "VARCHAR", shipping_method: "ENUM", status: "ENUM",
    estimated_delivery_date: "DATE", shipping_cost: "DECIMAL",
  },
  reviews: {
    id: "INT", product_id: "INT", user_id: "INT", order_id: "INT", rating: "TINYINT",
    title: "VARCHAR", is_verified_purchase: "TINYINT", helpful_votes: "INT", status: "ENUM", created_at: "DATETIME",
  },
};

export const tableKeys = {
  roles:             { pk: "id", fk: {} },
  users:             { pk: "id", fk: { role_id: "roles.id" } },
  vendors:           { pk: "id", fk: { user_id: "users.id" } },
  categories:        { pk: "id", fk: { parent_id: "categories.id" } },
  products:          { pk: "id", fk: { vendor_id: "vendors.id", category_id: "categories.id" } },
  product_inventory: { pk: "id", fk: { product_id: "products.id" } },
  carts:             { pk: "id", fk: { user_id: "users.id" } },
  cart_items:        { pk: "id", fk: { cart_id: "carts.id", product_id: "products.id" } },
  orders:            { pk: "id", fk: { user_id: "users.id" } },
  order_items:       { pk: "id", fk: { order_id: "orders.id", product_id: "products.id", vendor_id: "vendors.id" } },
  payments:          { pk: "id", fk: { order_id: "orders.id", user_id: "users.id" } },
  shipments:         { pk: "id", fk: { order_id: "orders.id", vendor_id: "vendors.id" } },
  reviews:           { pk: "id", fk: { product_id: "products.id", user_id: "users.id", order_id: "orders.id" } },
};

export const tableIcons = {
  roles: "🔐",
  users: "👤",
  vendors: "🏪",
  categories: "📂",
  products: "📦",
  product_inventory: "🏭",
  carts: "🛒",
  cart_items: "🧺",
  orders: "📋",
  order_items: "🧾",
  payments: "💳",
  shipments: "🚚",
  reviews: "⭐",
};

export const questions = [
  { id: "Q1",  text: "List all users who registered in the last 30 days.", tables: ["users"],
    answer: `SELECT *\nFROM users\nWHERE created_at >= DATE_SUB(NOW(), INTERVAL 30 DAY);` },
  { id: "Q2",  text: "Find all products with a price greater than ₹10,000.", tables: ["products"],
    answer: `SELECT *\nFROM products\nWHERE price > 10000;` },
  { id: "Q3",  text: "Retrieve all orders currently in 'delivered' status.", tables: ["orders"],
    answer: `SELECT *\nFROM orders\nWHERE order_status = 'delivered';` },
  { id: "Q4",  text: "Show all vendors whose status is 'active'.", tables: ["vendors"],
    answer: `SELECT *\nFROM vendors\nWHERE status = 'active';` },
  { id: "Q5",  text: "List all product categories along with their parent category name.", tables: ["categories"],
    answer: `SELECT\n    c.id,\n    c.name  AS category_name,\n    p.name  AS parent_category_name\nFROM categories c\nLEFT JOIN categories p ON c.parent_id = p.id;` },
  { id: "Q6",  text: "Find all customers (role = 'customer') who have verified their email.", tables: ["users", "roles"],
    answer: `SELECT u.*\nFROM users u\nJOIN roles r ON u.role_id = r.id\nWHERE r.name = 'customer'\n  AND u.is_email_verified = 1;` },
  { id: "Q7",  text: "Retrieve all products that belong to the 'Electronics' category.", tables: ["products", "categories"],
    answer: `SELECT p.*\nFROM products p\nJOIN categories c ON p.category_id = c.id\nWHERE c.name = 'Electronics';` },
  { id: "Q8",  text: "Show all orders placed by a specific user (user_id = 300).", tables: ["orders"],
    answer: `SELECT *\nFROM orders\nWHERE user_id = 300;` },
  { id: "Q9",  text: "List all cart items for a specific cart (cart_id = 50).", tables: ["cart_items"],
    answer: `SELECT *\nFROM cart_items\nWHERE cart_id = 50;` },
  { id: "Q10", text: "Find all reviews with a 5-star rating.", tables: ["reviews"],
    answer: `SELECT *\nFROM reviews\nWHERE rating = 5;` },
  { id: "Q11", text: "Retrieve all payments that failed.", tables: ["payments"],
    answer: `SELECT *\nFROM payments\nWHERE status = 'failed';` },
  { id: "Q12", text: "List all shipments handled by courier_partner = 'Delhivery'.", tables: ["shipments"],
    answer: `SELECT *\nFROM shipments\nWHERE courier_partner = 'Delhivery';` },
  { id: "Q13", text: "Find all products whose sale_price is NOT NULL (currently on discount).", tables: ["products"],
    answer: `SELECT *\nFROM products\nWHERE sale_price IS NOT NULL;` },
  { id: "Q14", text: "Show all users who have been banned.", tables: ["users"],
    answer: `SELECT *\nFROM users\nWHERE status = 'banned';` },
  { id: "Q15", text: "List all orders that used a coupon_code.", tables: ["orders"],
    answer: `SELECT *\nFROM orders\nWHERE coupon_code IS NOT NULL;` },
  { id: "Q16", text: "Retrieve the 10 most recently created products.", tables: ["products"],
    answer: `SELECT *\nFROM products\nORDER BY created_at DESC\nLIMIT 10;` },
  { id: "Q17", text: "Find all vendors located in the city 'Bangalore'.", tables: ["vendors"],
    answer: `SELECT *\nFROM vendors\nWHERE city = 'Bangalore';` },
  { id: "Q18", text: "Show all order_items for a specific order (order_id = 200).", tables: ["order_items"],
    answer: `SELECT *\nFROM order_items\nWHERE order_id = 200;` },
  { id: "Q19", text: "List all products in the 'Smartphones' sub-category.", tables: ["products", "categories"],
    answer: `SELECT p.*\nFROM products p\nJOIN categories c ON p.category_id = c.id\nWHERE c.name = 'Smartphones';` },
  { id: "Q20", text: "Retrieve all shipments currently in 'in_transit' status.", tables: ["shipments"],
    answer: `SELECT *\nFROM shipments\nWHERE status = 'in_transit';` },
  { id: "Q21", text: "Show all reviews that are pending moderation (status = 'pending').", tables: ["reviews"],
    answer: `SELECT *\nFROM reviews\nWHERE status = 'pending';` },
  { id: "Q22", text: "Find all products marked as featured (is_featured = 1).", tables: ["products"],
    answer: `SELECT *\nFROM products\nWHERE is_featured = 1;` },
  { id: "Q23", text: "List all orders where payment_status = 'paid'.", tables: ["orders"],
    answer: `SELECT *\nFROM orders\nWHERE payment_status = 'paid';` },
  { id: "Q24", text: "Retrieve all carts marked as 'abandoned'.", tables: ["carts"],
    answer: `SELECT *\nFROM carts\nWHERE status = 'abandoned';` },
  { id: "Q25", text: "Show the total count of products in the database.", tables: ["products"],
    answer: `SELECT COUNT(*) AS total_products\nFROM products;` },
  { id: "Q26", text: "Find all users whose phone number is NULL.", tables: ["users"],
    answer: `SELECT *\nFROM users\nWHERE phone IS NULL;` },
  { id: "Q27", text: "List all products with quantity_in_stock = 0 in the inventory table.", tables: ["products", "product_inventory"],
    answer: `SELECT p.*\nFROM products p\nJOIN product_inventory pi ON p.id = pi.product_id\nWHERE pi.quantity_in_stock = 0;` },
  { id: "Q28", text: "Show all orders created in the year 2024.", tables: ["orders"],
    answer: `SELECT *\nFROM orders\nWHERE YEAR(created_at) = 2024;` },
  { id: "Q29", text: "Retrieve all payments made via the 'upi' payment method.", tables: ["payments"],
    answer: `SELECT *\nFROM payments\nWHERE payment_method = 'upi';` },
  { id: "Q30", text: "List all products belonging to vendors with vendor_id between 10 and 20.", tables: ["products"],
    answer: `SELECT *\nFROM products\nWHERE vendor_id BETWEEN 10 AND 20;` },

  { id: "Q31", text: "Count total orders per order_status, sorted by count descending.", tables: ["orders"],
    answer: `SELECT\n    order_status,\n    COUNT(*) AS total_orders\nFROM orders\nGROUP BY order_status\nORDER BY total_orders DESC;` },
  { id: "Q32", text: "Calculate total revenue from all orders with payment_status = 'paid'.", tables: ["orders"],
    answer: `SELECT\n    SUM(total_amount) AS total_revenue\nFROM orders\nWHERE payment_status = 'paid';` },
  { id: "Q33", text: "Find the average product rating per product (using the reviews table).", tables: ["reviews"],
    answer: `SELECT\n    product_id,\n    ROUND(AVG(rating), 2) AS avg_rating,\n    COUNT(*)              AS review_count\nFROM reviews\nGROUP BY product_id\nORDER BY avg_rating DESC;` },
  { id: "Q34", text: "Show the number of products listed by each vendor, sorted highest first.", tables: ["products"],
    answer: `SELECT\n    vendor_id,\n    COUNT(*) AS product_count\nFROM products\nGROUP BY vendor_id\nORDER BY product_count DESC;` },
  { id: "Q35", text: "Find total orders placed per month in 2024.", tables: ["orders"],
    answer: `SELECT\n    MONTH(created_at)                AS month_number,\n    DATE_FORMAT(created_at, '%b %Y') AS month_label,\n    COUNT(*)                         AS total_orders\nFROM orders\nWHERE YEAR(created_at) = 2024\nGROUP BY MONTH(created_at), DATE_FORMAT(created_at, '%b %Y')\nORDER BY month_number;` },
  { id: "Q36", text: "Calculate total sales amount (SUM of total_price) per product from order_items.", tables: ["order_items"],
    answer: `SELECT\n    product_id,\n    SUM(total_price) AS total_sales_amount\nFROM order_items\nGROUP BY product_id\nORDER BY total_sales_amount DESC;` },
  { id: "Q37", text: "Find the top 5 categories by number of active products.", tables: ["categories", "products"],
    answer: `SELECT\n    c.id,\n    c.name          AS category_name,\n    COUNT(p.id)     AS active_product_count\nFROM categories c\nJOIN products p ON c.id = p.category_id\nWHERE p.status = 'active'\nGROUP BY c.id, c.name\nORDER BY active_product_count DESC\nLIMIT 5;` },
  { id: "Q38", text: "Show average order value per user — only users with 3 or more orders.", tables: ["orders"],
    answer: `SELECT\n    user_id,\n    COUNT(*)                    AS order_count,\n    ROUND(AVG(total_amount), 2) AS avg_order_value\nFROM orders\nGROUP BY user_id\nHAVING order_count >= 3\nORDER BY avg_order_value DESC;` },
  { id: "Q39", text: "Count failed payments per payment_gateway.", tables: ["payments"],
    answer: `SELECT\n    payment_gateway,\n    COUNT(*) AS failed_count\nFROM payments\nWHERE status = 'failed'\nGROUP BY payment_gateway\nORDER BY failed_count DESC;` },
  { id: "Q40", text: "Find all vendors who have listed more than 50 products.", tables: ["products"],
    answer: `SELECT\n    vendor_id,\n    COUNT(*) AS product_count\nFROM products\nGROUP BY vendor_id\nHAVING product_count > 50\nORDER BY product_count DESC;` },
  { id: "Q41", text: "Calculate the total refund_amount issued across all payments.", tables: ["payments"],
    answer: `SELECT\n    SUM(refund_amount) AS total_refund_amount\nFROM payments;` },
  { id: "Q42", text: "Show the number of reviews per rating value (1 through 5).", tables: ["reviews"],
    answer: `SELECT\n    rating,\n    COUNT(*) AS review_count\nFROM reviews\nGROUP BY rating\nORDER BY rating;` },
  { id: "Q43", text: "Find the total shipping_cost per courier_partner.", tables: ["shipments"],
    answer: `SELECT\n    courier_partner,\n    SUM(shipping_cost) AS total_shipping_cost\nFROM shipments\nGROUP BY courier_partner\nORDER BY total_shipping_cost DESC;` },
  { id: "Q44", text: "List products where discount percentage exceeds 30%.", tables: ["products"],
    answer: `SELECT\n    id,\n    title,\n    price,\n    sale_price,\n    ROUND((price - sale_price) / price * 100, 2) AS discount_pct\nFROM products\nWHERE sale_price IS NOT NULL\n  AND (price - sale_price) / price * 100 > 30\nORDER BY discount_pct DESC;` },
  { id: "Q45", text: "Count abandoned carts per user — show only users with 2 or more abandoned carts.", tables: ["carts"],
    answer: `SELECT\n    user_id,\n    COUNT(*) AS abandoned_count\nFROM carts\nWHERE status = 'abandoned'\nGROUP BY user_id\nHAVING abandoned_count >= 2\nORDER BY abandoned_count DESC;` },
  { id: "Q46", text: "Calculate total revenue per vendor for delivered orders only.", tables: ["order_items", "orders"],
    answer: `SELECT\n    oi.vendor_id,\n    SUM(oi.total_price) AS total_revenue\nFROM order_items oi\nJOIN orders o ON oi.order_id = o.id\nWHERE o.order_status = 'delivered'\nGROUP BY oi.vendor_id\nORDER BY total_revenue DESC;` },
  { id: "Q47", text: "Find the month with the highest number of new user registrations.", tables: ["users"],
    answer: `SELECT\n    DATE_FORMAT(created_at, '%b %Y') AS month_label,\n    COUNT(*)                         AS registrations\nFROM users\nGROUP BY DATE_FORMAT(created_at, '%b %Y'), YEAR(created_at), MONTH(created_at)\nORDER BY registrations DESC\nLIMIT 1;` },
  { id: "Q48", text: "Show products that have been reviewed more than 10 times.", tables: ["reviews"],
    answer: `SELECT\n    product_id,\n    COUNT(*) AS review_count\nFROM reviews\nGROUP BY product_id\nHAVING review_count > 10\nORDER BY review_count DESC;` },
  { id: "Q49", text: "Calculate the payment success rate (success / total) per payment_method.", tables: ["payments"],
    answer: `SELECT\n    payment_method,\n    COUNT(*)                                                        AS total_payments,\n    SUM(CASE WHEN status = 'success' THEN 1 ELSE 0 END)            AS successful,\n    ROUND(\n        SUM(CASE WHEN status = 'success' THEN 1 ELSE 0 END)\n        / COUNT(*) * 100, 2)                                        AS success_rate_pct\nFROM payments\nGROUP BY payment_method\nORDER BY success_rate_pct DESC;` },
  { id: "Q50", text: "Find the average delivery time in days for all delivered orders.", tables: ["orders"],
    answer: `SELECT\n    ROUND(AVG(DATEDIFF(delivered_at, created_at)), 2) AS avg_delivery_days\nFROM orders\nWHERE order_status = 'delivered'\n  AND delivered_at IS NOT NULL;` },
  { id: "Q51", text: "Show the number of orders placed per day of the week (Mon–Sun).", tables: ["orders"],
    answer: `SELECT\n    DAYOFWEEK(created_at) AS day_number,\n    DAYNAME(created_at)   AS day_name,\n    COUNT(*)              AS order_count\nFROM orders\nGROUP BY DAYOFWEEK(created_at), DAYNAME(created_at)\nORDER BY day_number;` },
  { id: "Q52", text: "Find the top 10 products by total quantity sold.", tables: ["order_items"],
    answer: `SELECT\n    product_id,\n    SUM(quantity) AS total_qty_sold\nFROM order_items\nGROUP BY product_id\nORDER BY total_qty_sold DESC\nLIMIT 10;` },
  { id: "Q53", text: "Calculate cart abandonment rate: abandoned carts ÷ total carts × 100.", tables: ["carts"],
    answer: `SELECT\n    COUNT(*)                                                        AS total_carts,\n    SUM(CASE WHEN status = 'abandoned' THEN 1 ELSE 0 END)          AS abandoned_carts,\n    ROUND(\n        SUM(CASE WHEN status = 'abandoned' THEN 1 ELSE 0 END)\n        / COUNT(*) * 100, 2)                                        AS abandonment_rate_pct\nFROM carts;` },
  { id: "Q54", text: "Show total revenue and order count grouped by order_status.", tables: ["orders"],
    answer: `SELECT\n    order_status,\n    COUNT(*)          AS order_count,\n    SUM(total_amount) AS total_revenue\nFROM orders\nGROUP BY order_status\nORDER BY total_revenue DESC;` },
  { id: "Q55", text: "Find vendors whose average product price exceeds ₹5,000.", tables: ["products"],
    answer: `SELECT\n    vendor_id,\n    ROUND(AVG(price), 2) AS avg_price\nFROM products\nGROUP BY vendor_id\nHAVING avg_price > 5000\nORDER BY avg_price DESC;` },
  { id: "Q56", text: "Count total products per category including sub-categories.", tables: ["categories", "products"],
    answer: `SELECT\n    c.id,\n    c.name          AS category_name,\n    COUNT(p.id)     AS product_count\nFROM categories c\nLEFT JOIN products p ON c.id = p.category_id\nGROUP BY c.id, c.name\nORDER BY product_count DESC;` },
  { id: "Q57", text: "Show number of shipments per shipping_method.", tables: ["shipments"],
    answer: `SELECT\n    shipping_method,\n    COUNT(*) AS shipment_count\nFROM shipments\nGROUP BY shipping_method\nORDER BY shipment_count DESC;` },
  { id: "Q58", text: "Find all orders where discount_amount > 500 and payment_status = 'paid'.", tables: ["orders"],
    answer: `SELECT *\nFROM orders\nWHERE discount_amount > 500\n  AND payment_status = 'paid';` },
  { id: "Q59", text: "Calculate the average vendor rating from reviews (joined through products).", tables: ["reviews", "products"],
    answer: `SELECT\n    p.vendor_id,\n    ROUND(AVG(r.rating), 2) AS avg_vendor_rating,\n    COUNT(r.id)             AS total_reviews\nFROM reviews r\nJOIN products p ON r.product_id = p.id\nGROUP BY p.vendor_id\nORDER BY avg_vendor_rating DESC;` },
  { id: "Q60", text: "Show total and average order value per quarter for the past year.", tables: ["orders"],
    answer: `SELECT\n    QUARTER(created_at)         AS quarter,\n    COUNT(*)                    AS order_count,\n    SUM(total_amount)           AS total_revenue,\n    ROUND(AVG(total_amount), 2) AS avg_order_value\nFROM orders\nWHERE created_at >= DATE_SUB(NOW(), INTERVAL 1 YEAR)\nGROUP BY QUARTER(created_at)\nORDER BY quarter;` },
  { id: "Q61", text: "Find products per vendor that are currently out of stock (quantity_in_stock = 0).", tables: ["products", "product_inventory"],
    answer: `SELECT\n    p.vendor_id,\n    COUNT(*) AS out_of_stock_count\nFROM products p\nJOIN product_inventory pi ON p.id = pi.product_id\nWHERE pi.quantity_in_stock = 0\nGROUP BY p.vendor_id\nORDER BY out_of_stock_count DESC;` },
  { id: "Q62", text: "List payment failure reasons with their frequency count.", tables: ["payments"],
    answer: `SELECT\n    failure_reason,\n    COUNT(*) AS frequency\nFROM payments\nWHERE status = 'failed'\n  AND failure_reason IS NOT NULL\nGROUP BY failure_reason\nORDER BY frequency DESC;` },
  { id: "Q63", text: "Show the percentage of orders that used a coupon_code.", tables: ["orders"],
    answer: `SELECT\n    COUNT(*)                                                        AS total_orders,\n    SUM(CASE WHEN coupon_code IS NOT NULL THEN 1 ELSE 0 END)       AS coupon_orders,\n    ROUND(\n        SUM(CASE WHEN coupon_code IS NOT NULL THEN 1 ELSE 0 END)\n        / COUNT(*) * 100, 2)                                        AS coupon_usage_pct\nFROM orders;` },
  { id: "Q64", text: "Find users who have placed orders but never written a review.", tables: ["orders", "reviews"],
    answer: `SELECT DISTINCT o.user_id\nFROM orders o\nLEFT JOIN reviews r ON o.user_id = r.user_id\nWHERE r.user_id IS NULL;` },
  { id: "Q65", text: "Calculate total tax collected per month.", tables: ["orders"],
    answer: `SELECT\n    DATE_FORMAT(created_at, '%b %Y') AS month_label,\n    SUM(tax_amount)                  AS total_tax\nFROM orders\nGROUP BY DATE_FORMAT(created_at, '%b %Y'), YEAR(created_at), MONTH(created_at)\nORDER BY YEAR(created_at), MONTH(created_at);` },
  { id: "Q66", text: "Show the top 5 vendor cities by total revenue.", tables: ["order_items", "vendors"],
    answer: `SELECT\n    v.city,\n    SUM(oi.total_price) AS total_revenue\nFROM order_items oi\nJOIN vendors v ON oi.vendor_id = v.id\nGROUP BY v.city\nORDER BY total_revenue DESC\nLIMIT 5;` },
  { id: "Q67", text: "Find the average number of items per order.", tables: ["order_items"],
    answer: `SELECT\n    ROUND(AVG(item_count), 2) AS avg_items_per_order\nFROM (\n    SELECT order_id, COUNT(*) AS item_count\n    FROM order_items\n    GROUP BY order_id\n) AS order_item_counts;` },
  { id: "Q68", text: "Count orders by both order_status and payment_status as a cross-tab matrix.", tables: ["orders"],
    answer: `SELECT\n    order_status,\n    SUM(CASE WHEN payment_status = 'pending'            THEN 1 ELSE 0 END) AS pay_pending,\n    SUM(CASE WHEN payment_status = 'paid'               THEN 1 ELSE 0 END) AS pay_paid,\n    SUM(CASE WHEN payment_status = 'failed'             THEN 1 ELSE 0 END) AS pay_failed,\n    SUM(CASE WHEN payment_status = 'refunded'           THEN 1 ELSE 0 END) AS pay_refunded,\n    SUM(CASE WHEN payment_status = 'partially_refunded' THEN 1 ELSE 0 END) AS pay_partial_refunded,\n    COUNT(*)                                                                AS row_total\nFROM orders\nGROUP BY order_status\nORDER BY order_status;` },
  { id: "Q69", text: "Show vendors ranked by commission_rate, highest first.", tables: ["vendors"],
    answer: `SELECT\n    id,\n    store_name,\n    commission_rate\nFROM vendors\nORDER BY commission_rate DESC;` },
  { id: "Q70", text: "Calculate total inventory value (quantity_in_stock × price) per category.", tables: ["categories", "products", "product_inventory"],
    answer: `SELECT\n    c.id,\n    c.name                              AS category_name,\n    SUM(pi.quantity_in_stock * p.price) AS total_inventory_value\nFROM categories c\nJOIN products p    ON c.id = p.category_id\nJOIN product_inventory pi ON p.id = pi.product_id\nGROUP BY c.id, c.name\nORDER BY total_inventory_value DESC;` },
];

export const statusColors = {
  active: "#22c55e",
  inactive: "#f59e0b",
  banned: "#ef4444",
  pending: "#f59e0b",
  confirmed: "#3b82f6",
  processing: "#8b5cf6",
  shipped: "#06b6d4",
  delivered: "#22c55e",
  cancelled: "#ef4444",
  refunded: "#f97316",
  success: "#22c55e",
  failed: "#ef4444",
  paid: "#22c55e",
  published: "#22c55e",
  rejected: "#ef4444",
  suspended: "#ef4444",
  converted: "#22c55e",
  abandoned: "#f59e0b",
  in_transit: "#06b6d4",
  dispatched: "#8b5cf6",
  packed: "#3b82f6",
  out_for_delivery: "#06b6d4",
  returned: "#f97316",
  lost: "#ef4444",
  draft: "#94a3b8",
  deleted: "#64748b",
  partially_refunded: "#f97316",
  // payment_method
  upi:         "#8b5cf6",
  credit_card: "#3b82f6",
  debit_card:  "#06b6d4",
  netbanking:  "#f59e0b",
  wallet:      "#22c55e",
  cod:         "#94a3b8",
  emi:         "#ec4899",
  // payment_gateway
  razorpay:  "#3b82f6",
  stripe:    "#8b5cf6",
  paytm:     "#06b6d4",
  cashfree:  "#22c55e",
  paypal:    "#f59e0b",
};
